package:
  name: diprofile
  version: "1.0"

source:
  url: http://194.135.91.6/archive/v1.0.tar
  sha256: 19c46d6bc6a1af70e5a2b4a051aab334026dc38c84b367ea9c445da3fdb21cfe

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - seqan-library
    - cmake
    - openmp

  host:
    - zlib
    - bzip2
    - openmp

  run:
    - zlib
    - bzip2
    - openmp
    
test:
  commands:
    - diprofile --help 

about:
  home: https://github.com/erinijapranckeviciene/dnpatterntools
  license: MIT
  summary: "Dinucleotide frequency of occurrence in a batch of fasta sequences"
